### ISSUE TITLE
Dongle ID create randomly 

### ISSUE THREAD

**Issue by munirfromdhaka** [garronej/chan-dongle-extended-pages#4]
Hello again,

I attached few modem with chan-dongle-extended, Sometime it recognize my all dongle some it don't and also create random Dongle id in asterisk so its hard to label any dongle so if anyone crush its hard to recognize the crushed dongle. so is that possible to fixed  the Dongle id with imei number always same?

Thanks in advance   

![dongle id](https://user-images.githubusercontent.com/67871475/155016636-b615ddf2-99e5-40b3-8804-07cd2439ace1.jpg)

**Comment by garronej** [comment]
Hi,

Dongle crash are usually related to power supply.  
Buy a good usb2 hub with external power supply and you should be good to go.  If you don't know which one to buy I can recommend a model.
I advise you, if possible, to use the cli tool (`dongle list` `dongle --help` ) rather than Asterisk for debugging.

**Comment by munirfromdhaka** [comment]
Hello,

Thanks for your quick reply. Actually my main question was, is that possible to name the Dongle id as i want to. In chan-dongle-extended it create automatically but I want to do it manually like i do manually in dongle.conf  so I can remember easily.

**Comment by garronej** [comment]
I don't think it is possible. 😕
